/*
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH6:+HMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH6:+bMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMH+:+bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM6:::jMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMb.:::jHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH6:::jHMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMj.::::::6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHj::.:jMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMH::.::::::bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM6:.:::jHMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMj::..:::+::jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHj:.::.:bMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMH+..:::::::::+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHj:.::::jMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+:::::::.::.::6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM6::.:++:+bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMM+..::::::..:::.:bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHj::.:j+j:6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMj:.::::::+:.:.::...+HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMb+...:66jj+6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMM+::::::::::::..............::+bMMMMMMMMMMMMMMMMMMMMMMMMMMMMb+..:+6H6b6:6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMM6..:::::::::.::..jjj6jj++::::::::.:+bMMMMMMMMMMMMMMMMMMMH+..:.+HH6jj++jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMb:::::::::....:::.............::...........:+j6bbbb6j:....:+bMHb6+:jj+HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMH:..:+++::::::::.....::+j6j+++:...........:::+:...:.....:+6MH66j++6666bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMM6::::::::.::.....:+j+:............................:j6j+bHMMMb6j+j6bbbb6MMMMMMMMb66j6bMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM+.:::........+j:.:...............................:::j6j6MHb6b+66bbbbbbbMH6+:++6b6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMb:.::+:.....:jj.......................:.........:6bHH6+j6MHbj+j6j6bbb6+:::j66bHbbMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMM6:::::....+j+.........................::....::j6bHbbbbHHMHb6::::++::::jbHb66HHbMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM6:::....:++:........................:..:::+66bHHHHMMHHMMMbH6H6:+++6bHHb666bHb6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM+:::...j+...........................:.:::jbbHHHHMMMMMMMMMHb++:j6HMHHb6j6bHb6bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM+.::..+j..................:....::...:::j6bHb6j6HMMMMMMMMb6j+jbMMMb6666bbbbbbMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMj....:b+.................:...:.:.:::+6bHHHHHbbHHbb6j666bHHbbjjbbbbbbbj6b66bbMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMj::..j:.......::..........::....::+bbHHHHHHHHMMHMHHbHMMMMMMbb+6j66++66666HbMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM6.:.++.........::......:...::::+6bbHHHHHHbHHMMMMMMMMMMMMMMHbb+:++j6b6jj6bbMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM:.+:............::...:...:.+6bbbHHHHHbHHHMMMMMMMMMMMMMMHbbbHHbMHMHbbHb6jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMb:................::......:+jbHHHHHHHHb6j6HHHHMMMMMMMHb6bbH666HbMbb6bb6bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMH:..................:...::+j6bbHHHbHHHH6jb66jbbbbHb66bbbbjj6b6bbHb66bjHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMH:........:..........:::+6bbHHbHbHHMMMMMMH66Hbj+jjjj6H6++jHb6bjb6bbHbMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMH:..................::+bbHbHbHHHMMMMMMMMMH66bbbb6j6+.+jjjjj666H66jHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMM6............:....:+j6j+::.................::+jjj66+:bHHj++jj++6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMj.................::+j6b6bbb6bb66j666j6666j6+:..jjj++::jbbb++HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMj.......:+jbbHHHMHHMMMMMHHMHbbbbHHbbHHHbbHb6j+++:+6bj:jj+::+:+::+bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMM+.:+6bHHb6++:jbbbHMMMMMMMMMMMMMMMMMMMMMMMMHHbbj+j6:+jHMMMMMMMHbjjj++:6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMj:jH6+:......:jbbHMMMMMMMMMMMMMMMMMMMMMMMHbbbbb66bb:+:HMMMMMMMMMMMMMMMMH66+jHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MbHMMM.....:.:jbHHMMMMMMMMMMMMMMMMMMMMHHHHHHH6666bjbb+MjjMMMMMMMMMMMMMMMMMMMMMMMH6+HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMH:....:+bHHHMMMMMMMMMMMMMMMMMMMHHHMbb6b66bHjHMj6MM+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMM6....:+bHHMMMMMMMMMMMMMMMMMMHHMHbbb6bMMMb6HMHjMMMHHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMb.:.:+bHMMMMMMMMMMMMMMMMHHHMHHMHMMMH6HMMMMM6MMMMMbMMMMMMMMMMMMMMMMMMMMMMMMMMH+bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMM..:+6bMMMMMMMMMMMMMMHHMHHHMHMHHj:.:HMMMMH6MMMMMbHMMMMMMMMMMMMMMMMMMMMMMMMb:jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMM+.:+66MMMMMMMMMMMMHHHHMHMHMMb:::...+MMMbHMMMMMMbMMMMMMMMMMMMMMMMMMMMMMMM::6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMb:+jj6b6HMMMMMMMHHHbbbbHM6:....:j:..bMHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMj:.jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMM6+j++j6bHHHMMMHbbb6bMMb.........+:.:HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH:..+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMM6+:+jj6bbMHHHbbb6bMb............:j..bMMMMMMMMMMMMMMMMMMMMMMMMMMMMj....MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMbbjj+j66bHb6666M+..:....:........:+.:HMMMMMMMMMMMMMMMMMMMMMMMMM:..:.jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMHjj+++j++6jj6H.::jj+..:...........:+.+MMMMMMMMMMMMMMMMMMMMMMM+.::.jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM66j+++++jjb:.+jjbb6b+.............+j.+HMMMMMMMMMMMMMMMMMMH:....:HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMb6666::j6..::jbHHbHb6j+............:6:...:6bHHMMMMMMMMM6:....:6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMM6+6+jj..:++jjbHbHHbb6j+:............++:.....6MMMMMMMH:.....+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM6+j:...:::+j6bHHHMbb66j:............:j+....6MMMMMH:......6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM.......::++jbbHHHMHbbbb6++:............+6+..+HMMj......:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM.:..::..:::++jbbbbMHMHHHbb6jj+:............:+j+:.......+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM::.++++:::::::+jj6bHHHMHMMHHHbbb6+:..............::.:..6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM::.++jjj6jj6+::+++j+jj66bbHHHHHHHHbbbj+::..............bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMM+:++jjj6j+:.::6bbbb66j6jj++jjj6666b66bbHbbbbbb66j+::...jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMj+j+jjjjHMMMMHj+++::+j6bHMMbbbbbb6b6jjjjjj66++::+jjj+:.6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMH+jjjjbMMMMMMMMMMMMMMMMMMMH+j6j+:.::::::::jj6666:::....6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMj:j6jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH+:::HMMMMMMMj......:HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMH+:+bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMHbMMMMMMMMM+.:::::bMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMM+:jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+.....+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMjjMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM6....:+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMM6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM6...:.jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMb..:..jMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMb:..::6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH:...:6MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
*/
namespace Marlin
{
    using System.Threading.Tasks;
    using org.apache.hadoop.hbase.rest.protobuf.generated;
    using ProtoBuf;

    /// <summary>
    /// Marlin is a C# connector to HBase. 
    /// 
    /// It currently targets HBase 0.96.2 and HDInsight 3.0 on Microsoft Azure.
    /// The communication works through HBase REST (StarGate) which uses ProtoBuf as a serialization format.
    /// 
    /// The usage is quite simple:
    /// 
    /// <code>
    /// var credentials = ClusterCredentials.FromFile("credentials.txt");
    /// var marlin = new Marlin(credentials);
    /// 
    /// var version = await marlin.GetVersionAsync();
    /// 
    /// Console.WriteLine(version);
    /// 
    /// </code>
    /// </summary>
    public class Marlin
    {
        private readonly ClusterCredentials _credentials;
        private readonly WebRequester _requester;

        public Marlin(ClusterCredentials credentials)
        {
            if (credentials == null)
            {
                throw new System.ArgumentNullException("credentials");
            }
            _credentials = credentials;
            _requester = new WebRequester(credentials);
        }

        public Version GetVersion()
        {
            return GetVersionAsync().Result;
        }

        public async Task<Version> GetVersionAsync()
        {
            using (var responseStream = await _requester.IssueWebRequestAsync("version"))
            {
                return Serializer.Deserialize<Version>(responseStream);
            }
        }
    }
}
